#!/usr/bin/env ruby

require 'rubygems'
require 'optparse'
require 'pry'
require_relative 'src/application.rb'

user_args = {}
opt_parser = OptionParser.new do |opt|
  opt.banner = "Usage example: ruby sudoku_solver
\nFor additional information please visit:\nhttps://github.com/simplay/sudoku_solver"
  opt.separator ""

  opt.on("-m", "--map m", String, "filename of sudoku map stored in maps/") do |mapname|
    user_args[:mapname] = mapname
  end

  opt.on_tail("-h", "--help", "Show this message") do
    puts opt
    exit
  end
end

begin
  opt_parser.parse!
rescue OptionParser::MissingArgument
  puts "Incorrect input argument(s) passed\n"
  puts opt_parser.help
  exit
end
Application.new(user_args[:mapname])

